parameters:
    ez_core_extra.themes.list: []
    ez_core_extra.themes.design_list: []
    ez_core_extra.themes.path_map: {}
    ez_core_extra.themes.assets_path_map: {}
    ez_core_extra.themes.override_paths: []
    ez_core_extra.themes.assets_override_paths: []
    ez_theme.asset_resolved_paths: {}
    ez_theme.asset_resolution.disabled: '%kernel.debug%'

    ez_core_extra.default.design: ~
    ez_core_extra.default.twig_globals: {}
