parameters:

services:
    ez_core_extra.view_template_listener:
        class: Lolautruche\EzCoreExtraBundle\EventListener\ViewTemplateListener
        arguments: ["@ezpublish.config.resolver", "@ezpublish.config.dynamic_setting.parser"]
        tags:
            - { name: kernel.event_subscriber }

    ez_core_extra.template_name_resolver:
        class: Lolautruche\EzCoreExtraBundle\Templating\ThemeTemplateNameResolver
        arguments: ["$design;ez_core_extra$"]
        lazy: true

    ez_core_extra.twig_theme_loader:
        class: Lolautruche\EzCoreExtraBundle\Templating\Twig\TwigThemeLoader
        public: false
        decorates: twig.loader.filesystem
        arguments:
            - "@ez_core_extra.template_name_resolver"
            - "@ez_core_extra.twig_theme_loader.inner"
            - "@templating.locator"
            - "@templating.name_parser"

    ez_core_extra.asset_path_resolver:
        class: Lolautruche\EzCoreExtraBundle\Asset\AssetPathResolver
        arguments:
            - "%ez_core_extra.themes.assets_path_map%"
            - "%webroot_dir%"

    ez_core_extra.asset_theme_package:
        class: Lolautruche\EzCoreExtraBundle\Asset\ThemePackage
        arguments:
            - "@ez_core_extra.asset_path_resolver"
            - "@assets._default_package"
        calls:
            - [setCurrentDesign, ["$design;ez_core_extra$"]]

    ez_core_extra.twig.globals_extension:
        class: Lolautruche\EzCoreExtraBundle\Templating\Twig\TwigGlobalsExtension
        calls:
            - [setContextAwareGlobals, ["$twig_globals;ez_core_extra$"]]
        tags:
            - { name: twig.extension }

    ez_core_extra.security.simplified_core_voter:
        class: Lolautruche\EzCoreExtraBundle\Security\Voter\SimplifiedCoreVoter
        arguments:
            - "@ezpublish.security.voter.core"
            - "@ezpublish.security.voter.value_object"
        tags:
            - { name: "security.voter" }
