language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

sudo: false

branches:
    only:
        - master
        - /^\d+\.\d+$/

env:
    - EZ_KERNEL_VERSION=^6.0

matrix:
    include:
        - php: 5.6
          env: EZ_KERNEL_VERSION=~2014.11
        - php: 7.0
          env: EZ_KERNEL_VERSION=^6.0
        - php: 7.1
          env: EZ_KERNEL_VERSION=^6.9

install:
    - phpenv config-rm xdebug.ini
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer require "ezsystems/ezpublish-kernel:${EZ_KERNEL_VERSION}" --no-update
    - composer install

script:
    - php vendor/bin/phpunit
