language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.6
    - 7.0

branches:
    only:
        - master
        - /^\d+\.\d+$/

env:
    - EZ_KERNEL_VERSION=^6.0

install:
    - phpenv config-rm xdebug.ini
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer require "ezsystems/ezpublish-kernel:${EZ_KERNEL_VERSION}" --no-update
    - composer install

script:
    - phpunit
